# CSR: Compressed Sparse Row für dünnbesetzte Matrizen

In [2]:
import numpy as np

In [7]:
matrix = np.array([[1, 4, 0, 0, 1],
                    [0, 0, 0, 0, 0],
                    [0, 5, 6, 0, 0],
                    [0, 0, 3, 0, 0]])
matrix


array([[1, 4, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 5, 6, 0, 0],
       [0, 0, 3, 0, 0]])

In [8]:
vector = np.array([3, 4, 5, 6, 7])
vector

array([3, 4, 5, 6, 7])

In [10]:
# Matrix-Vector-Multiply:
# For each row in matrix: Multiply pairwise elements with vector
matrix @ vector

array([26,  0, 50, 15])

In [22]:
# CSR-Representation
# val: Non-zero values in Reihenfolge der Matrix (zeilenweise)
val = np.array([1, 4, 1, 5, 6, 3])
# col_index: in welcher Spalte steht der jeweilige Wert?
col_index = np.array([0, 1, 4, 1, 2, 2])
# row_ptr: bei welchen Index startet die Zeile? 
# Wenn nur Nullen in einer Zeile, dann Index der nächsten Zeile
# Zusätzliches Element mit Anzahl der Non-Zero Values
row_ptr = np.array([0, 3, 3, 5, 6])

In [27]:
# Result contains one row per row in the matrix (first dim of matrix, shape[0])
result = np.zeros(matrix.shape[0])
for row in range(matrix.shape[0]):
    # In each row we do pairwise elements multiplication
    # what are all the entries belonging to one row?
    # We start at row_ptr[row] and end before beginning of next row
    for ptr in range(row_ptr[row], row_ptr[row+1]):
        # To know which position in the vector to take, we look at col_index
        result[row] += val[ptr] * vector[col_index[ptr]]
result


array([26.,  0., 50., 15.])